DELETE FROM wish;
DELETE FROM option;
DELETE FROM product;
DELETE FROM member;
DELETE FROM category;

ALTER TABLE wish ALTER COLUMN id RESTART WITH 1;
ALTER TABLE option ALTER COLUMN id RESTART WITH 1;
ALTER TABLE product ALTER COLUMN id RESTART WITH 1;
ALTER TABLE member ALTER COLUMN id RESTART WITH 1;
ALTER TABLE category ALTER COLUMN id RESTART WITH 1;
